### ISSUE TITLE
scala-js failure since May 20, 2015

### ISSUE THREAD

**Issue by retronym** [scala/community-builds#100]
https://jenkins-dbuild.typesafe.com:8499/view/Shared/job/Community-2.11.x/554/consoleFull

```
[scala-js] Testing: jasmineTestFramework
[scala-js] org.mozilla.javascript.EcmaError: ReferenceError: "x" is not defined. (s_Array$.sjsir#78)
[scala-js] 	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3701)
[scala-js] 	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3679)
[scala-js] 	at org.mozilla.javascript.ScriptRuntime.notFoundError(ScriptRuntime.java:3764)
[scala-js] 	at org.mozilla.javascript.ScriptRuntime.nameOrFunction(ScriptRuntime.java:1805)
[scala-js] 	at org.mozilla.javascript.ScriptRuntime.name(ScriptRuntime.java:1744)
[scala-js] 	at org.mozilla.javascript.gen.s_Array__sjsir_295._c_anonymous_17(s_Array$.sjsir:78)
[scala-js] 	at org.mozilla.javascript.gen.s_Array__sjsir_295.call(s_Array$.sjsir)
[scala-js] 	at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
[scala-js] 	at org.mozilla.javascript.gen.Lorg_scalajs_jasminetest_JasmineFramework_sjsir_31._c_anonymous_6(Lorg_scalajs_jasminetest_JasmineFramework.sjsir:28)
[scala-js] 	at org.mozilla.javascript.gen.Lorg_scalajs_jasminetest_JasmineFramework_sjsir_31.call(Lorg_scalajs_jasminetest_JasmineFramework.sjsir)
[scala-js] 	at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:85)
[scala-js] 	at org.mozilla.javascript.gen.Lorg_scalajs_testinterface_internal_InfoSender_sjsir_26._c_anonymous_6(Lorg_scalajs_testinterface_internal_InfoSender.sjsir:25)
[scala-js] 	at org.mozilla.javascript.gen.Lorg_scalajs_testinterface_internal_InfoSender_sjsir_26.call(Lorg_scalajs_testinterface_internal_InfoSender.sjsir)
[scala-js] 	at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:85)
[scala-js] 	at org.mozilla.javascript.gen.Lorg_scalajs_testinterface_internal_InfoSender_sjsir_26._c_anonymous_3(Lorg_scalajs_testinterface_internal_InfoSender.sjsir:20)
[scala-js] 	at org.mozilla.javascript.gen.Lorg_scalajs_testinterface_internal_InfoSender_sjsir_26.call(Lorg_scalajs_testinterface_internal_InfoSender.sjsir)
[scala-js] 	at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:85)
[scala-js] 	at org.mozilla.javascript.gen.Lorg_scalajs_testinterface_internal_InfoSender_sjsir_26._c_anonymous_9(Lorg_scalajs_testinterface_internal_InfoSender.sjsir:38)
[scala-js] 	at org.mozilla.javascript.gen.Lorg_scalajs_testinterface_internal_InfoSender_sjsir_26.call(Lorg_scalajs_testinterface_internal_InfoSender.sjsir)
[scala-js] 	at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:85)
[scala-js] 	at org.mozilla.javascript.gen.Lorg_scalajs_testinterface_internal_InfoSender_sjsir_26._c_anonymous_14(Lorg_scalajs_testinterface_internal_InfoSender.sjsir:55)
[scala-js] 	at org.mozilla.javascript.gen.Lorg_scalajs_testinterface_internal_InfoSender_sjsir_26.call(Lorg_scalajs_testinterface_internal_InfoSender.sjsir)
[scala-js] 	at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:85)
[scala-js] 	at org.mozilla.javascript.gen.testFrameworkInfo_js_33._c_script_0(testFrameworkInfo.js:2)
[scala-js] 	at org.mozilla.javascript.gen.testFrameworkInfo_js_33.call(testFrameworkInfo.js)
[scala-js] 	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
[scala-js] 	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3102)
[scala-js] 	at org.mozilla.javascript.gen.testFrameworkInfo_js_33.call(testFrameworkInfo.js)
[scala-js] 	at org.mozilla.javascript.gen.testFrameworkInfo_js_33.exec(testFrameworkInfo.js)
[scala-js] 	at org.mozilla.javascript.Context.evaluateString(Context.java:1078)
[scala-js] 	at org.scalajs.jsenv.rhino.package$ContextOps$.evaluateFile$extension(package.scala:21)
[scala-js] 	at org.scalajs.jsenv.rhino.RhinoJSEnv.org$scalajs$jsenv$rhino$RhinoJSEnv$$internalRunJS(RhinoJSEnv.scala:152)
[scala-js] 	at org.scalajs.jsenv.rhino.RhinoJSEnv$AsyncRunner$$anon$1.run(RhinoJSEnv.scala:76)
[scala-js] java.lang.RuntimeException: Exception while running JS code: ReferenceError: "x" is not defined. (s_Array$.sjsir#78)
[scala-js] 	at scala.sys.package$.error(package.scala:27)
[scala-js] 	at org.scalajs.jsenv.rhino.RhinoJSEnv.org$scalajs$jsenv$rhino$RhinoJSEnv$$internalRunJS(RhinoJSEnv.scala:168)
[scala-js] 	at org.scalajs.jsenv.rhino.RhinoJSEnv$AsyncRunner$$anon$1.run(RhinoJSEnv.scala:76)
[scala-js] [error] (jasmineTestFramework/test:loadedTestFrameworks) Exception while running JS code: ReferenceError: "x" is not defined. (s_Array$.sjsir#78)
[scala-js:error] Incomplete(node=Some(ScopedKey(Scope(Select(ProjectRef(file:/mnt/dbuild/jenkinsdbuild3/localhome-a8/workspace/Community-2.11.x/target-0.9.1/project-builds/scala-js-e4b1c28b19a5e8e22dc4dee7106f8e3034da47a4/,jasmineTestFramework)),Select(ConfigKey(test)),Global,Global),test)), tpe=Error, msg=None, causes=List(Incomplete(node=Some(ScopedKey(Scope(Select(ProjectRef(file:/mnt/dbuild/jenkinsdbuild3/localhome-a8/workspace/Community-2.11.x/target-0.9.1/project-builds/scala-js-e4b1c28b19a5e8e22dc4dee7106f8e3034da47a4/,jasmineTestFramework)),Select(ConfigKey(test)),Global,Global),executeTests)), tpe=Error, msg=None, causes=List(Incomplete(node=Some(ScopedKey(Scope(Select(ProjectRef(file:/mnt/dbuild/jenkinsdbuild3/localhome-a8/workspace/Community-2.11.x/target-0.9.1/project-builds/scala-js-e4b1c28b19a5e8e22dc4dee7106f8e3034da47a4/,jasmineTestFramework)),Select(ConfigKey(test)),Global,Global),loadedTestFrameworks)), tpe=Error, msg=None, causes=List(), directCause=Some(java.lang.RuntimeException: Exception while running JS code: ReferenceError: "x" is not defined. (s_Array$.sjsir#78))), Incomplete(node=Some(ScopedKey(Scope(Global,Global,Global,Global),testGrouping)), tpe=Error, msg=None, causes=List(Incomplete(node=Some(ScopedKey(Scope(Select(ProjectRef(file:/mnt/dbuild/jenkinsdbuild3/localhome-a8/workspace/Community-2.11.x/target-0.9.1/project-builds/scala-js-e4b1c28b19a5e8e22dc4dee7106f8e3034da47a4/,jasmineTestFramework)),Select(ConfigKey(test)),Global,Global),definedTests)), tpe=Error, msg=None, causes=List(Incomplete(node=Some(ScopedKey(Scope(Select(ProjectRef(file:/mnt/dbuild/jenkinsdbuild3/localhome-a8/workspace/Community-2.11.x/target-0.9.1/project-builds/scala-js-e4b1c28b19a5e8e22dc4dee7106f8e3034da47a4/,jasmineTestFramework)),Select(ConfigKey(test)),Global,Global),loadedTestFrameworks)), tpe=Error, msg=None, causes=List(), directCause=Some(java.lang.RuntimeException: Exception while running JS code: ReferenceError: "x" is not defined. (s_Array$.sjsir#78)))), directCause=None)), directCause=None)), directCause=None)), directCause=None)
[scala-js:error] 	at sbt.Incomplete.copy(Incomplete.scala:17)
[scala-js:error] 	at sbt.EvaluateTask$$anonfun$taskToKey$1.apply(EvaluateTask.scala:383)
[scala-js:error] 	at sbt.EvaluateTask$$anonfun$taskToKey$1.apply(EvaluateTask.scala:382)
[scala-js:error] 	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:55)
[scala-js:error] 	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:55)
[scala-js:error] 	at sbt.Incomplete$$anonfun$sbt$Incomplete$$visit$1$1.apply(Incomplete.scala:32)
[scala-js:error] 	at sbt.Incomplete$$anonfun$sbt$Incomplete$$visit$1$1.apply(Incomplete.scala:32)
[scala-js:error] 	at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:189)
[scala-js:error] 	at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:91)
[scala-js:error] 	at sbt.Incomplete$.sbt$Incomplete$$visit$1(Incomplete.scala:32)
[scala-js:error] 	at sbt.Incomplete$.transform(Incomplete.scala:36)
[scala-js:error] 	at sbt.Incomplete$.transformBU(Incomplete.scala:26)
[scala-js:error] 	at sbt.EvaluateTask$$anonfun$transformInc$1.apply(EvaluateTask.scala:381)
[scala-js:error] 	at sbt.EvaluateTask$$anonfun$transformInc$1.apply(EvaluateTask.scala:381)
[scala-js:error] 	at scala.util.Either$LeftProjection.map(Either.scala:377)
[scala-js:error] 	at sbt.EvaluateTask$.transformInc(EvaluateTask.scala:381)
[scala-js:error] 	at sbt.EvaluateTask$.run$1(EvaluateTask.scala:347)
[scala-js:error] 	at sbt.EvaluateTask$.runTask(EvaluateTask.scala:361)
[scala-js:error] 	at sbt.EvaluateTask$$anonfun$apply$1$$anonfun$apply$3.apply(EvaluateTask.scala:258)
[scala-js:error] 	at sbt.EvaluateTask$$anonfun$apply$1$$anonfun$apply$3.apply(EvaluateTask.scala:258)
[scala-js:error] 	at scala.Option$WithFilter.map(Option.scala:206)
[scala-js:error] 	at sbt.EvaluateTask$$anonfun$apply$1.apply(EvaluateTask.scala:258)
[scala-js:error] 	at sbt.EvaluateTask$$anonfun$apply$1.apply(EvaluateTask.scala:257)
[scala-js:error] 	at sbt.EvaluateTask$.withStreams(EvaluateTask.scala:293)
[scala-js:error] 	at sbt.EvaluateTask$.apply(EvaluateTask.scala:257)
[scala-js:error] 	at sbt.EvaluateTask$.apply(EvaluateTask.scala:255)
[scala-js:error] 	at sbt.Extracted.runTask(Extracted.scala:43)
[scala-js:error] 	at com.typesafe.dbuild.DistributedRunner$.com$typesafe$dbuild$DistributedRunner$$buildTestPublish$1(DistributedRunner.scala:596)
[scala-js:error] 	at com.typesafe.dbuild.DistributedRunner$$anonfun$19.apply(DistributedRunner.scala:616)
[scala-js:error] 	at com.typesafe.dbuild.DistributedRunner$$anonfun$19.apply(DistributedRunner.scala:616)
[scala-js:error] 	at com.typesafe.dbuild.DistributedRunner$$anonfun$com$typesafe$dbuild$DistributedRunner$$runAggregate$1.apply(DistributedRunner.scala:70)
[scala-js:error] 	at com.typesafe.dbuild.DistributedRunner$$anonfun$com$typesafe$dbuild$DistributedRunner$$runAggregate$1.apply(DistributedRunner.scala:67)
[scala-js:error] 	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:111)
[scala-js:error] 	at scala.collection.immutable.List.foldLeft(List.scala:84)
[scala-js:error] 	at com.typesafe.dbuild.DistributedRunner$.com$typesafe$dbuild$DistributedRunner$$runAggregate(DistributedRunner.scala:67)
[scala-js:error] 	at com.typesafe.dbuild.DistributedRunner$$anonfun$14.apply(DistributedRunner.scala:574)
[scala-js:error] 	at com.typesafe.dbuild.DistributedRunner$$anonfun$14.apply(DistributedRunner.scala:574)
[scala-js:error] 	at com.typesafe.dbuild.DistributedRunner$.buildStuff(DistributedRunner.scala:616)
[scala-js:error] 	at com.typesafe.dbuild.DistributedRunner$$anonfun$generateArtifacts$1.apply(DistributedRunner.scala:745)
[scala-js:error] 	at com.typesafe.dbuild.DistributedRunner$$anonfun$generateArtifacts$1.apply(DistributedRunner.scala:745)
[scala-js:error] 	at com.typesafe.dbuild.StateHelpers$.saveLastMsg(StateHelpers.scala:35)
[scala-js:error] 	at com.typesafe.dbuild.DistributedRunner$.generateArtifacts(DistributedRunner.scala:745)
[scala-js:error] 	at com.typesafe.dbuild.DistributedRunner$$anonfun$com$typesafe$dbuild$DistributedRunner$$buildIt$1.apply(DistributedRunner.scala:749)
[scala-js:error] 	at com.typesafe.dbuild.DistributedRunner$$anonfun$com$typesafe$dbuild$DistributedRunner$$buildIt$1.apply(DistributedRunner.scala:749)
[scala-js:error] 	at sbt.Command$$anonfun$command$1$$anonfun$apply$1.apply(Command.scala:29)
[scala-js:error] 	at sbt.Command$$anonfun$command$1$$anonfun$apply$1.apply(Command.scala:29)
[scala-js:error] 	at sbt.Command$.process(Command.scala:92)
[scala-js:error] 	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
[scala-js:error] 	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
[scala-js:error] 	at sbt.State$$anon$1.process(State.scala:184)
[scala-js:error] 	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
[scala-js:error] 	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
[scala-js:error] 	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[scala-js:error] 	at sbt.MainLoop$.next(MainLoop.scala:98)
[scala-js:error] 	at sbt.MainLoop$.run(MainLoop.scala:91)
[scala-js:error] 	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
[scala-js:error] 	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
[scala-js:error] 	at sbt.Using.apply(Using.scala:24)
[scala-js:error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
[scala-js:error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
[scala-js:error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
[scala-js:error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:24)
[scala-js:error] 	at sbt.StandardMain$.runManaged(Main.scala:53)
[scala-js:error] 	at sbt.xMain.run(Main.scala:28)
[scala-js:error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:57)
[scala-js:error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:77)
[scala-js:error] 	at xsbt.boot.Launch$.run(Launch.scala:57)
[scala-js:error] 	at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:45)
[scala-js:error] 	at xsbt.boot.Launch$.launch(Launch.scala:65)
[scala-js:error] 	at xsbt.boot.Launch$.apply(Launch.scala:16)
[scala-js:error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:32)
[scala-js:error] 	at xsbt.boot.Boot$.main(Boot.scala:21)
[scala-js:error] 	at xsbt.boot.Boot.main(Boot.scala)
[scala-js:error] java.lang.RuntimeException: 
[scala-js:error] 	at scala.sys.package$.error(package.scala:27)
[scala-js:error] 	at distributed.support.sbt.SbtRunner.distributed$support$sbt$SbtRunner$$processCommand(SbtRunner.scala:93)
[scala-js:error] 	at distributed.support.sbt.SbtRunner$$anonfun$run$1$$anonfun$apply$2$$anonfun$apply$3.apply(SbtRunner.scala:74)
[scala-js:error] 	at distributed.support.sbt.SbtRunner$$anonfun$run$1$$anonfun$apply$2$$anonfun$apply$3.apply(SbtRunner.scala:74)
[scala-js:error] 	at distributed.support.sbt.SbtRunner$$anonfun$run$1.apply(SbtRunner.scala:74)
[scala-js:error] 	at distributed.support.sbt.SbtRunner$$anonfun$run$1.apply(SbtRunner.scala:64)
[scala-js:error] 	at sbt.IO$.withTemporaryFile(IO.scala:311)
[scala-js:error] 	at distributed.support.sbt.SbtRunner.run(SbtRunner.scala:64)
[scala-js:error] 	at distributed.support.sbt.SbtBuilder$.buildSbtProject(SbtBuildRunner.scala:84)
[scala-js:error] 	at distributed.support.sbt.SbtBuildSystem.runBuild(SbtBuildSystem.scala:68)
[scala-js:error] 	at distributed.support.sbt.SbtBuildSystem.runBuild(SbtBuildSystem.scala:18)
[scala-js] --== End Building scala-js ==--
```

**Comment by retronym** [comment]
@sjrd Does this look familiar to you?

**Comment by retronym** [comment]
http://github.com/scala-js/scala-js/commit6dbab2c3ebb665efe0c1eee2af33202d6edc42e2

**Comment by retronym** [comment]
But, that build successfully the day before. Could it be a change in scala/scala?

**Comment by retronym** [comment]
The diff in the repeatable config:

```
--- { (Selection)
+++ (clipboard)
@@ -2764,7 +2764,7 @@
                                 "cross-version" : [
                                     "disabled"
                                 ],
-                                "uri" : "https://github.com/scala/scala.git#454a1dcf0c3568ea99f669529b4819782b8b2f00"
+                                "uri" : "https://github.com/scala/scala.git#f635ba91d641d900ffd56ae0f4bbfb8e88bfe2d1"
                             },
                             {
                                 "system" : "sbt",
```

**Comment by retronym** [comment]
https://github.com/scala/scala/compare/454a1dcf0c3568ea99f669529b4819782b8b2f00...f635ba91d641d900ffd56ae0f4bbfb8e88bfe2d1

**Comment by retronym** [comment]
This is reproducible with:

```diff
diff --git a/project/Build.scala b/project/Build.scala
index dffaa16..edc0492 100644
--- a/project/Build.scala
+++ b/project/Build.scala
@@ -47,7 +47,8 @@ object Build extends sbt.Build {
     ScalaJSCrossVersion.binaryScalaJSVersion(previousVersion)

   val commonSettings = Seq(
-      scalaVersion := "2.11.6",
+      scalaVersion := "2.11.7-SNAPSHOT",
+      scalaBinaryVersion := "2.11",
       organization := "org.scala-js",
       version := scalaJSVersion,
```

**Comment by sjrd** [comment]
Does not seem familiar. I will investigate this in a couple hours when I'm at work, in front of a computer.

**Comment by retronym** [comment]
Thanks. Would love it if you keep a share a few notes on how you diagnose this problem, so we can learn a little bit about ScalaJS in the process.

**Comment by sjrd** [comment]
OK, so after having reproduced, this is how I approach such an issue.
First, a coarse dichotomic search to attribute the blame to one of the major components of the pipeline. Basically, the pipeline is as follows:

1. scalac until mixin, included
2. Scala.js compiler plugin -> produces .sjsir files
3. Linker: all the .sjsir files on the classpath are brought together and linked
4. Optimizer: optimizes the linked program
5. Desugar/emitter: transform the IR into a JS AST and print it

So, this is the typical search:
* Verify the linked IR with `testSuite/test:fastOptJS (similar to the Validation performed by the JVM)
  * If the IR verifies, then disable the optimizer.
    * If that succeeds, blame the optimizer (unlikely in this case, because it fails with Rhino anyway, which doesn't use the optimizer in the first place -- but typically we do everything with Node.js)
    * If it still fails, blame Desugar
  * If the IR does not verify, then print some of the IR that does not validate, to validate "manually"
    * If it validates by hand, blame the linker and/or IR checker
    * If it doesn't validate by hand, then inspect the scalac trees after mixin (`-Xprint:mixin`)
      * If that looks OK, blame the Scala.js compiler plugin
      * If it looks funny, blame scalac (or a macro)

So, in this case, the IR does not validate. The full errors are in this gist:
https://gist.github.com/sjrd/33717376fe91398e2e1d
but I'll concentrate on these:
```
[error] .../scala/util/hashing/MurmurHash3.scala(91:20:VarRef): Cannot find variable x in scope
[error] .../scala/util/hashing/MurmurHash3.scala(91:20:VarRef): Cannot find variable a in scope
[error] .../scala/util/hashing/MurmurHash3.scala(109:20:VarRef): Cannot find variable x in scope
[error] .../scala/util/hashing/MurmurHash3.scala(109:20:VarRef): Cannot find variable n in scope
```
because I know that `MurmurHash3` is a pretty simple file. So I go to that file and look at lines 91 and 109. They are the lines with `foreach` in these two methods.
```scala
  final def unorderedHash(xs: TraversableOnce[Any], seed: Int): Int = {
    var a, b, n = 0
    var c = 1
    xs foreach { x =>
      val h = x.##
      a += h
      b ^= h
      if (h != 0) c *= h
      n += 1
    }
    var h = seed
    h = mix(h, a)
    h = mix(h, b)
    h = mixLast(h, c)
    finalizeHash(h, n)
  }
  /** Compute a hash that depends on the order of its arguments.
   */
  final def orderedHash(xs: TraversableOnce[Any], seed: Int): Int = {
    var n = 0
    var h = seed
    xs foreach { x =>
      h = mix(h, x.##)
      n += 1
    }
    finalizeHash(h, n)
  }
```
OK now let's see the IR for `orderedHash`, which is the simplest, with scalajsp:
```scala
> cli/runMain org.scalajs.cli.Scalajsp scalalib/target/scala-2.11/classes/scala/util/hashing/MurmurHash3.sjsir
[info] Running org.scalajs.cli.Scalajsp scalalib/target/scala-2.11/classes/scala/util/hashing/MurmurHash3.sjsir
  def orderedHash__sc_TraversableOnce__I__I(xs: sc_TraversableOnce, seed: int): int = {
    val n: sr_IntRef = mod:sr_IntRef$.create__I__sr_IntRef(0);
    val h: sr_IntRef = mod:sr_IntRef$.create__I__sr_IntRef(seed);
    xs.foreach__F1__V(new sjsr_AnonFunction1().init___sjs_js_Function1((lambda<this, h, x>(this$2: s_util_hashing_MurmurHash3, h: sr_IntRef, x: any, x$2: any) = {
      val x: any = x$2;
      this$2.$$anonfun$2__p1__sr_IntRef__sr_IntRef__O__V(n, h, x);
      (void 0)
    })));
    this.finalizeHash__I__I__I(h.elem$1, n.elem$1)
  }

```
There is obviously a problem with `x` in the lambda. A lambda is basically a JavaScript anonymous function, where captures are explicitly stated in the `<>`. Every capture is an expression from the surrounding scope, and is captured as the corresponding "formal parameter" of the lambda. The remaining formal parameters are the real formal parameters or the generated function (OK, the notation may not be clear).

Here, we refer to `x` in the expressions captured from the surrounding scope, in `<this, h, x>`, but `x` is not declared outside the lambda. Indeed, it is actually declared inside as `val x: any = x$2`.

So, at this point, I want to have a look at the scalac tree before mixin. Since I don't want to do that for all of the scala lib, I'll just copy the offending snippet in the Helloworld example, which is my sandbox. Since it involves lambdas, I make sure to use the `-Ydelambdafy:method` when compiling the Helloworld (by default, this flag is used when compiling the library, but not the examples):
```
> set scalacOptions in helloworld ++= Seq("-Ydelambdafy:method", "-Xprint:mixin")
[info] Defining helloworld/*:scalacOptions
[info] The new value will be used by helloworld/compile:scalacOptions
[info] Reapplying settings...
[info] Set current project to Scala.js (in build file:/localhome/doeraene/projects/scalajs/)
> helloworld/fastOptJS
[info] Updating {file:/localhome/doeraene/projects/scalajs/}helloworld...
[info] Resolving org.eclipse.jetty#jetty-continuation;8.1.16.v20140903 ...
[info] Done updating.
[info] Resolving org.eclipse.jetty#jetty-continuation;8.1.16.v20140903 ...
[info] Compiling 1 Scala source to /localhome/doeraene/projects/scalajs/examples/helloworld/target/scala-2.11/classes...
[[syntax trees at end of                     mixin]] // HelloWorld.scala
package helloworld {
  object HelloWorld extends Object with scalajs.js.JSApp {
    <synthetic> def $js$exported$meth$main(): Object = scala.scalajs.js.JSApp$class.$js$exported$meth$main(HelloWorld.this);
    final def orderedHash(xs: scala.collection.TraversableOnce, seed: Int): Int = {
      var n: runtime.IntRef = scala.runtime.IntRef.create(0);
      var h: runtime.IntRef = scala.runtime.IntRef.create(seed);
      xs.foreach({
        ((x: Object) => HelloWorld.this.$anonfun$1(n, h, x)).$asInstanceOf[Function1]()
      });
      scala.util.hashing.MurmurHash3.finalizeHash(h.elem, n.elem)
    };
    def main(): Unit = {
      HelloWorld.this.orderedHash(immutable.this.Nil, 0);
      ()
    };
    final <artifact> private[this] def $anonfun$1(n$1: runtime.IntRef, h$1: runtime.IntRef, x: Object): Unit = {
      h$1.elem = scala.util.hashing.MurmurHash3.mix(h$1.elem, runtime.this.ScalaRunTime.hash(x));
      n$1.elem = n$1.elem.+(1)
    };
    def <init>(): helloworld.HelloWorld.type = {
      HelloWorld.super.<init>();
      scala.scalajs.js.JSApp$class./*JSApp$class*/$init$(HelloWorld.this);
      ()
    }
  }
}

[info] Fast optimizing /localhome/doeraene/projects/scalajs/examples/helloworld/target/scala-2.11/helloworld-fastopt.js
[error] file:/localhome/doeraene/projects/scalajs/library/src/main/scala/scala/scalajs/runtime/package.scala(67:23:VarRef): Cannot find variable x in scope
[error] file:/localhome/doeraene/projects/scalajs/library/src/main/scala/scala/scalajs/runtime/package.scala(67:23:VarRef): Cannot find variable result in scope
[error] file:/localhome/doeraene/projects/scalajs/examples/helloworld/HelloWorld.scala(15:20:VarRef): Cannot find variable x in scope
[error] file:/localhome/doeraene/projects/scalajs/examples/helloworld/HelloWorld.scala(15:20:VarRef): Cannot find variable n in scope
[error] https://raw.githubusercontent.com/scala/scala/v2.11.7-SNAPSHOT/src/library/scala/util/hashing/MurmurHash3.scala(109:20:VarRef): Cannot find variable x in scope
[error] https://raw.githubusercontent.com/scala/scala/v2.11.7-SNAPSHOT/src/library/scala/util/hashing/MurmurHash3.scala(109:20:VarRef): Cannot find variable n in scope
[error] https://raw.githubusercontent.com/scala/scala/v2.11.7-SNAPSHOT/src/library/scala/collection/TraversableOnce.scala(355:12:VarRef): Cannot find variable x in scope
[error] https://raw.githubusercontent.com/scala/scala/v2.11.7-SNAPSHOT/src/library/scala/collection/TraversableOnce.scala(355:12:VarRef): Cannot find variable first in scope
[trace] Stack trace suppressed: run last helloworld/compile:fastOptJS for the full output.
[error] (helloworld/compile:fastOptJS) There were 8 IR checking errors.
[error] Total time: 22 s, completed May 20, 2015 10:19:35 AM
```
OK so the output after `mixin` seems reasonable (and I can reproduce the linking errors in the sandbox), so I would blame the Scala.js compiler plugin.

Now, I happen to know that the compiler plugin does tricky things with `Function` nodes emitted by `-Ydelambdafy:method`. And it is likely that little variations in the scheme are going to break it (I mentioned that on the PR that initially introduced `-Ydelambdafy:method` ages ago, I think). So let's look at that code:
https://github.com/scala-js/scala-js/blob/a8a926bf80c24d7e42ae45973149d1967c61f88f/compiler/src/main/scala/org/scalajs/core/compiler/GenJSCode.scala#L3747
Oh look! There's even a big comment explaining what we expect to receive from scalac. Let's see if the tree from mixin matches our expectations:

> Anonymous functions survive until the backend only under `-Ydelambdafy:method` and when they do, their body is always of the form `EnclosingClass.this.someMethod(arg1, ..., argN, capture1, ..., captureM)` where argI are the formal arguments of the lambda, and captureI are local variables or the enclosing def.

and the tree:
```scala
      xs.foreach({
        ((x: Object) => HelloWorld.this.$anonfun$1(n, h, x)).$asInstanceOf[Function1]()
      });
```
Oh ow, big mismatch. The captures have now come to the front, and the formal parameters went to the end. Ouch.

So *yes*, it came from a change in scalac. But *no*, it's probably not scalac's *fault*. The Scala.js compiler plugin should probably be adapted to the new ordering. How to do that right now (while still staying source compatible with older versions of Scala), I don't know yet, but I'll figure it out.

What I really don't understand is what change in scala/scala could *possibly* have changed the order, in the diff you mentioned. Do you have any idea?

**Comment by retronym** [comment]
Epic writeup, @sjrd. /cc @adriaanm @lrytz @sethtisue

This was the compiler change that change the parameter order: https://github.com/scala/scala/commit/1e7a990e028dffc5fa8ac07a02ff3f79bde24749

**Comment by adriaanm** [comment]
+1 thanks for writing it down so nicely -- helped improve my understanding of the scala.js pipeline!
