### ISSUE TITLE
2.13: try to get pfps-shopping-cart over the finish line

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#1039]
over at #1033 I ran into this error. it isn't obvious to me what might be causing it

rather than hold up that massive PR over one repo, I will mark the repo as "expected to fail". lodging this ticket and hopefully I can return to it

```
[pfps-shopping-cart] [error] /Users/tisue/community.213/target-0.9.16/project-builds/pfps-shopping-cart-ef667029c01fde679d6996e8ea4def1dec809a19/modules/core/src/main/scala/shop/config/loader.scala:67:18: exception during macro expansion: 
[pfps-shopping-cart] [error] java.lang.AssertionError: assertion failed: import failure: cannot determine unique overloaded method alternative from
[pfps-shopping-cart] [error]  final package eu
[pfps-shopping-cart] [error] final package eu
[pfps-shopping-cart] [error]  that matches package eu:eu.type
[pfps-shopping-cart] [error] 	at scala.reflect.internal.SymbolTable.throwAssertionError(SymbolTable.scala:170)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.disambiguate$1(Importers.scala:195)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.recreateOrRelink$1(Importers.scala:200)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.importSymbol(Importers.scala:222)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.recreateOrRelink$1(Importers.scala:181)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.importSymbol(Importers.scala:222)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.recreateOrRelink$1(Importers.scala:178)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.importSymbol(Importers.scala:222)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.recreateOrRelink$1(Importers.scala:178)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.importSymbol(Importers.scala:222)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.recreateOrRelink$1(Importers.scala:178)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.importSymbol(Importers.scala:222)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.recreatedTreeCompleter(Importers.scala:310)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.$anonfun$importTree$1(Importers.scala:429)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.tryFixup(Importers.scala:61)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.importTree(Importers.scala:430)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.recreateTree(Importers.scala:395)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.importTree(Importers.scala:427)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.recreateTree(Importers.scala:395)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.importTree(Importers.scala:427)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.recreateTree(Importers.scala:379)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.importTree(Importers.scala:427)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.recreateTree(Importers.scala:382)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.importTree(Importers.scala:427)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.importTree(Importers.scala:41)
[pfps-shopping-cart] [error] 	at scala.reflect.macros.contexts.Evals.eval(Evals.scala:31)
[pfps-shopping-cart] [error] 	at scala.reflect.macros.contexts.Evals.eval$(Evals.scala:26)
[pfps-shopping-cart] [error] 	at scala.reflect.macros.contexts.Context.eval(Context.scala:18)
[pfps-shopping-cart] [error] 	at eu.timepit.refined.macros.MacroUtils.$anonfun$eval$1(MacroUtils.scala:22)
[pfps-shopping-cart] [error] 	at scala.Option.getOrElse(Option.scala:201)
[pfps-shopping-cart] [error] 	at eu.timepit.refined.macros.MacroUtils.tryN(MacroUtils.scala:26)
[pfps-shopping-cart] [error] 	at eu.timepit.refined.macros.MacroUtils.tryN$(MacroUtils.scala:25)
[pfps-shopping-cart] [error] 	at eu.timepit.refined.macros.RefineMacro.tryN(RefineMacro.scala:10)
[pfps-shopping-cart] [error] 	at eu.timepit.refined.macros.MacroUtils.eval(MacroUtils.scala:22)
[pfps-shopping-cart] [error] 	at eu.timepit.refined.macros.MacroUtils.eval$(MacroUtils.scala:15)
[pfps-shopping-cart] [error] 	at eu.timepit.refined.macros.RefineMacro.eval(RefineMacro.scala:10)
[pfps-shopping-cart] [error] 	at eu.timepit.refined.macros.RefineMacro.$anonfun$validateInstance$2(RefineMacro.scala:55)
[pfps-shopping-cart] [error] 	at scala.Option.getOrElse(Option.scala:201)
[pfps-shopping-cart] [error] 	at eu.timepit.refined.macros.RefineMacro.validateInstance(RefineMacro.scala:55)
[pfps-shopping-cart] [error] 	at eu.timepit.refined.macros.RefineMacro.impl(RefineMacro.scala:25)
[pfps-shopping-cart] [error]           port = 5432,
[pfps-shopping-cart] [error]                  ^
```

**Comment by SethTisue** [comment]
rather than let pfps-shopping-cart hold up this whole PR, I've marked it as expected-to-fail and opened a separate ticket on it: #1039

**Comment by SethTisue** [comment]
new PR: #1040

**Comment by SethTisue** [comment]
I ran this locally and the error mentions a different package name:

```
[pfps-shopping-cart] [error] /Users/tisue/community.213/target-0.9.16/project-builds/pfps-shopping-cart-116b80224e63deb86dba88ddacf8d9f95c89df6b/modules/core/src/main/scala/shop/config/loader.scala:67:18: exception during macro expansion: 
[pfps-shopping-cart] [error] java.lang.AssertionError: assertion failed: import failure: cannot determine unique overloaded method alternative from
[pfps-shopping-cart] [error]  final package shapeless
[pfps-shopping-cart] [error] final package shapeless
[pfps-shopping-cart] [error]  that matches package shapeless:shapeless.type
[pfps-shopping-cart] [error] 	at scala.reflect.internal.SymbolTable.throwAssertionError(SymbolTable.scala:170)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.disambiguate$1(Importers.scala:195)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.recreateOrRelink$1(Importers.scala:200)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.importSymbol(Importers.scala:222)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.recreatedTreeCompleter(Importers.scala:310)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.$anonfun$importTree$1(Importers.scala:429)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.tryFixup(Importers.scala:61)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.importTree(Importers.scala:430)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.recreateTree(Importers.scala:395)
[pfps-shopping-cart] [error] 	at scala.reflect.internal.Importers$StandardImporter.importTree(Importers.scala:427)
```

**Comment by SethTisue** [comment]
ah, there's a ticket on this at https://github.com/fthomas/refined/issues/260

**Comment by SethTisue** [comment]
this seems like a refined issue rather than anything I should delve into any further myself, so I'm going to close this and leave the project as expected-to-fail

**Comment by SethTisue** [comment]
pfps-shopping-cart is green these days on 2.13.x, and I don't recall seeing this error (not even intermittently) in recent months
