### ISSUE TITLE
2.13: scala-pet-store is failing

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#1042]
I merged #1040 regardless, but I should still try and fix this unless it's a can of worms

https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/3045/artifact/logs/scala-pet-store-build.log

```
[scala-pet-store] Processing subproject: default-sbt-project
[scala-pet-store] [error] **** Missing dependency: the library org.scalatestplus#scalatestplus-scalacheck is not provided (in space "default") by any project in this configuration file.
[scala-pet-store] [error] In order to control which version is used, please add the corresponding project to the build file
[scala-pet-store] [error] (or use "check-missing:false" to ignore (not recommended)).
[scala-pet-store] [error] java.lang.RuntimeException: Required dependency not found
```

**Comment by SethTisue** [comment]
I tried to fix this as follows.

I forked scala-pet-store to use ScalaTest 3.1 and the right scalatestplus-scalacheck artifact name

that fixed the above error, but then in trying to run scala-pet-store's tests we get:

```
[scala-pet-store] [info] io.github.pauljamescleary.petstore.infrastructure.repository.doobie.UserQueryTypeCheckSpec *** ABORTED ***
[scala-pet-store] [info]   java.lang.AbstractMethodError: Method io/github/pauljamescleary/petstore/infrastructure/repository/doobie/UserQueryTypeCheckSpec.org$scalatest$Assertions$_setter_$assertionsHelper_$eq(Lorg/scalatest/Assertions$AssertionsHelper;)V is abstract
[scala-pet-store] [info]   at io.github.pauljamescleary.petstore.infrastructure.repository.doobie.UserQueryTypeCheckSpec.org$scalatest$Assertions$_setter_$assertionsHelper_$eq(UserQueryTypeCheckSpec.scala)
[scala-pet-store] [info]   at org.scalatest.Assertions.$init$(Assertions.scala:527)
[scala-pet-store] [info]   at org.scalatest.funsuite.AnyFunSuite.<init>(AnyFunSuite.scala:1562)
```

I made one attempt to fix this; I thought it might be a doobie version mismatch, somehow. scala-pet-store currently expects doobie v0.8.8, so I forked doobie from that tag, applied the Scala 2.13.1-friendliness changes that Rob already made on master, and then ran the build again, but it didn't help, same error.

I can't afford to spend any more time on this, so I think the "solution" here will be that we compile scala-pet-store tests, but don't attempt to run them. it's still valuable to have the repo, regardless.

fyi @pauljamescleary @zakpatterson
