### ISSUE TITLE
Spire running out of heap in 2.12 community build

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#316]
https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/685/consoleFull has

```
[spire:error] java.lang.OutOfMemoryError: Java heap space
[spire:error]   at scala.tools.asm.Frame.merge(Frame.java:1293)
[spire:error]   at scala.tools.asm.MethodWriter.visitMaxs(MethodWriter.java:1483)
[spire:error]   at scala.tools.asm.tree.MethodNode.accept(MethodNode.java:835)
[spire] [error] Error while emitting spire/math/interval/ValueBound$
[spire] [error] Java heap space
[spire:error]   at scala.tools.asm.tree.MethodNode.accept(MethodNode.java:727)
[spire:error]   at scala.tools.asm.tree.ClassNode.accept(ClassNode.java:412)
[spire:error]   at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase$Worker2.getByteArray$1(GenBCode.scala:291)
[spire:error]   at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase$Worker2.addToQ3(GenBCode.scala:298)
[spire:error]   at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase$Worker2.run(GenBCode.scala:274)
[spire:error]   at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase.buildAndSendToDisk(GenBCode.scala:384)
[spire:error]   at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase.run(GenBCode.scala:350)
[spire:error]   at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1404)
```

**Comment by SethTisue** [comment]
it might be random lossage because too many jobs at once rather than anything Spire specific?
<img width="216" alt="screen shot 2016-09-28 at 11 26 31 am" src="https://cloud.githubusercontent.com/assets/161079/18926921/78157d1e-856e-11e6-898a-b552052cf45a.png">

**Comment by SethTisue** [comment]
provisionally closing on the assumption it's just https://github.com/scala/scala-jenkins-infra/issues/181 as usual :-\
