### ISSUE TITLE
regression: ssl-config test suite often hangs

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#560]
at e.g. https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/474/consoleFull

I've also seen this locally on my Mac

```
[ssl-config] [info] 
Warning: system did not shut down within the allotted time
An exception occurred.
akka.pattern.AskTimeoutException: Timed out
	at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:312)
	at akka.actor.DefaultScheduler$$anon$8.run(Scheduler.scala:191)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:137)
	at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:506)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by SethTisue** [comment]
disabled running the tests in cd3c22d27ba31b38386a7b74b2562d2522fc5492

**Comment by SethTisue** [comment]
@wsargent @ktoso I see there are no recent commits in the ssl-config repository. perhaps this caused by a regression elsewhere?

```
[info] Project ssl-config
[info]   depends on: akka, genjavadoc, kind-projector, macro-compat, macro-paradise, pcplod,
  scala, scala-java8-compat, scala-parser-combinators, scalacheck, scalatest, scalaz,
  shapeless, specs2
```

**Comment by SethTisue** [comment]
closing this ticket since disabling the tests made the community build green again; y'all ssl-config maintainers can decide if there's something further here that needs pursuing

**Comment by wsargent** [comment]
:-/

**Comment by SethTisue** [comment]
as we saw at #666 recently, this still happens if the tests are enabled
