### ISSUE TITLE
regression (2.12): compilation failure (NPE in StringTypeTag.typeToString) building zinc

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#597]
seen at https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/1896/consoleFull

```
[zinc] Running "compile" in: jar2
[zinc] [error] java.lang.NullPointerException
[zinc] [error] 	at sbt.internal.util.StringTypeTag$.typeToString(StringTypeTag.scala:27)
[zinc] [error] 	at sbt.internal.util.StringTypeTag$.apply(StringTypeTag.scala:15)
[zinc] [error] 	at sbt.internal.util.ManagedLogger.registerStringCodec(ManagedLogger.scala:39)
[zinc] [error] 	at sbt.internal.util.ManagedLogger.<init>(ManagedLogger.scala:46)
[zinc] [error] 	at sbt.util.LogExchange.logger(LogExchange.scala:32)
[zinc] [error] 	at sbt.internal.LogManager$.defaultLogger(LogManager.scala:122)
[zinc] [error] 	at sbt.internal.LogManager$DefaultLogManager.apply(LogManager.scala:99)
[zinc] [error] 	at sbt.internal.LogManager$.$anonfun$construct$1(LogManager.scala:47)
[zinc] [error] 	at sbt.std.Streams$$anon$3$$anon$2.log(Streams.scala:173)
[zinc] [error] 	at sbt.std.TaskStreams.log(Streams.scala:88)
[zinc] [error] 	at sbt.std.TaskStreams.log$(Streams.scala:88)
[zinc] [error] 	at sbt.std.Streams$$anon$3$$anon$2.log$lzycompute(Streams.scala:137)
[zinc] [error] 	at sbt.std.Streams$$anon$3$$anon$2.log(Streams.scala:137)
[zinc] [error] 	at sbt.Classpaths$.$anonfun$depMap$1(Defaults.scala:2436)
[zinc] [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[zinc] [error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[zinc] [error] 	at sbt.std.Transform$$anon$4.work(System.scala:64)
[zinc] [error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[zinc] [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[zinc] [error] 	at sbt.Execute.work(Execute.scala:266)
[zinc] [error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[zinc] [error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[zinc] [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[zinc] [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[zinc] [error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[zinc] [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[zinc] [error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[zinc] [error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[zinc] [error] 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by SethTisue** [comment]
huh. it went away in the next run. I won't worry about it

**Comment by SethTisue** [comment]
weird, I saw this in a local run just now, but in sbt-librarymanagement instead of zinc:

```
[sbt-librarymanagement] [info] Loading settings from ÿÿÿÿÿÿÿÿÿÿ~~~~dbuild~defs.sbt ...
[sbt-librarymanagement] [info] Loading project definition from /Users/tisue/community-builds.212/target-0.9.9/project-builds/sbt-librarymanagement-d4cc998f4c12514597339e29bd5d6e6605bbcd46/project/project
[sbt-librarymanagement] [error] java.lang.NullPointerException
[sbt-librarymanagement] [error] 	at sbt.internal.util.StringTypeTag$.typeToString(StringTypeTag.scala:27)
[sbt-librarymanagement] [error] 	at sbt.internal.util.StringTypeTag$.apply(StringTypeTag.scala:15)
[sbt-librarymanagement] [error] 	at sbt.internal.util.ManagedLogger.registerStringCodec(ManagedLogger.scala:39)
[sbt-librarymanagement] [error] 	at sbt.internal.util.ManagedLogger.<init>(ManagedLogger.scala:45)
[sbt-librarymanagement] [error] 	at sbt.util.LogExchange.logger(LogExchange.scala:32)
[sbt-librarymanagement] [error] 	at sbt.internal.LogManager$.defaultLogger(LogManager.scala:122)
[sbt-librarymanagement] [error] 	at sbt.internal.LogManager$DefaultLogManager.apply(LogManager.scala:99)
[sbt-librarymanagement] [error] 	at sbt.internal.LogManager$.$anonfun$construct$1(LogManager.scala:47)
[sbt-librarymanagement] [error] 	at sbt.std.Streams$$anon$3$$anon$2.log(Streams.scala:173)
[sbt-librarymanagement] [error] 	at sbt.std.TaskStreams.log(Streams.scala:88)
[sbt-librarymanagement] [error] 	at sbt.std.TaskStreams.log$(Streams.scala:88)
[sbt-librarymanagement] [error] 	at sbt.std.Streams$$anon$3$$anon$2.log$lzycompute(Streams.scala:137)
[sbt-librarymanagement] [error] 	at sbt.std.Streams$$anon$3$$anon$2.log(Streams.scala:137)
[sbt-librarymanagement] [error] 	at sbt.Classpaths$.$anonfun$depMap$1(Defaults.scala:2436)
[sbt-librarymanagement] [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[sbt-librarymanagement] [error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[sbt-librarymanagement] [error] 	at sbt.std.Transform$$anon$4.work(System.scala:64)
[sbt-librarymanagement] [error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[sbt-librarymanagement] [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[sbt-librarymanagement] [error] 	at sbt.Execute.work(Execute.scala:266)
[sbt-librarymanagement] [error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[sbt-librarymanagement] [error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[sbt-librarymanagement] [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[sbt-librarymanagement] [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[sbt-librarymanagement] [error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[sbt-librarymanagement] [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[sbt-librarymanagement] [error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[sbt-librarymanagement] [error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[sbt-librarymanagement] [error] 	at java.lang.Thread.run(Thread.java:748)
[sbt-librarymanagement] [error] (*:projectDescriptors) java.lang.NullPointerException
```

**Comment by SethTisue** [comment]
oh, the underlying cause is https://github.com/sbt/util/issues/119 . so upgrading the community build to sbt 1.0.1 (for those projects that we build with 1.0.x at all, which at the moment is just sbt and its modules) should take care of it. I'll do that now
