### ISSUE TITLE
Unresolved dependency in spray when building locally

### ISSUE THREAD

**Issue by sjrd** [scala/community-builds#78]
I've been trying to build the community build locally for some time with

    $ ./community-2.11.x.sh -l

as I was advised in #64. I could never get it working (with various revisions of the master branch), due to an unresolved dependency during the extraction of `spray`. All other projects extract fine, but the build is still stuck because extraction as a whole failed.

I get this log for the spray part:
```
[spray] --== Extracting dependencies for spray ==--
[spray] Fetching https://github.com/spray/spray.git
[spray] into /localhome/doeraene/projects/community-builds/target-0.9.1/clones/b21fb93a57f49c1ce50294e594fdf7ccc44cf04e
[spray] Took: 00h 00m 02.0s
[spray] Cloning /localhome/doeraene/projects/community-builds/target-0.9.1/clones/b21fb93a57f49c1ce50294e594fdf7ccc44cf04e
[spray] to /localhome/doeraene/projects/community-builds/target-0.9.1/extraction/0d4f8866a9919fb3fe53ee2783b05700b261171c/projects/b25cc2edc52bfb154641e6458db0d6982db45693
[spray] Took: 00h 00m 00.0s
[spray] Fetching /localhome/doeraene/projects/community-builds/target-0.9.1/clones/b21fb93a57f49c1ce50294e594fdf7ccc44cf04e
[spray] into /localhome/doeraene/projects/community-builds/target-0.9.1/extraction/0d4f8866a9919fb3fe53ee2783b05700b261171c/projects/b25cc2edc52bfb154641e6458db0d6982db45693
[spray] Took: 00h 00m 00.2s
[spray] Extracting dependencies for: spray
[spray] Using Scala 2.11.2 during extraction.
[spray] Using sbt version: 0.13.5
[spray] [info] Loading project definition from /localhome/doeraene/projects/community-builds/target-0.9.1/extraction/0d4f8866a9919fb3fe53ee2783b05700b261171c/projects/b25cc2edc52bfb154641e6458db0d6982db45693/project/project
[spray] [info] Updating {file:/localhome/doeraene/projects/community-builds/target-0.9.1/extraction/0d4f8866a9919fb3fe53ee2783b05700b261171c/projects/b25cc2edc52bfb154641e6458db0d6982db45693/project/project/}b25cc2edc52bfb154641e6458db0d6982db45693-build-build...
[spray] [info] Done updating.
[spray] [info] Loading project definition from /localhome/doeraene/projects/community-builds/target-0.9.1/extraction/0d4f8866a9919fb3fe53ee2783b05700b261171c/projects/b25cc2edc52bfb154641e6458db0d6982db45693/project
[spray] [info] Resetting onLoad... in one scope
[spray] [info] Loading project definition from /localhome/doeraene/projects/community-builds/target-0.9.1/extraction/0d4f8866a9919fb3fe53ee2783b05700b261171c/projects/b25cc2edc52bfb154641e6458db0d6982db45693/project
[spray] [info] Dependencies among subprojects:
[spray] [info] default-sbt-project -> 
[spray] [info] Aggregates of subprojects:
[spray] [info] default-sbt-project -> 
[spray] [info] Building graph...
[spray] [info] sorting...
[spray] [info] These subprojects will be built: default-sbt-project
[spray] [info] Updating {file:/localhome/doeraene/projects/community-builds/target-0.9.1/extraction/0d4f8866a9919fb3fe53ee2783b05700b261171c/projects/b25cc2edc52bfb154641e6458db0d6982db45693/project/}b25cc2edc52bfb154641e6458db0d6982db45693-build...
[spray] [warn]  module not found: com.decodified#scala-ssh_2.10;0.6.4
[spray] [warn] ==== local: tried
[spray] [warn]   /home/doeraene/.ivy2/local/com.decodified/scala-ssh_2.10/0.6.4/ivys/ivy.xml
[spray] [warn] ==== public: tried
[spray] [warn]   http://repo1.maven.org/maven2/com/decodified/scala-ssh_2.10/0.6.4/scala-ssh_2.10-0.6.4.pom
[spray] [warn] ==== sonatype-snapshots: tried
[spray] [warn]   https://oss.sonatype.org/content/repositories/snapshots/com/decodified/scala-ssh_2.10/0.6.4/scala-ssh_2.10-0.6.4.pom
[spray] [warn] ==== sonatype-releases: tried
[spray] [warn]   https://oss.sonatype.org/content/repositories/releases/com/decodified/scala-ssh_2.10/0.6.4/scala-ssh_2.10-0.6.4.pom
[spray] [warn] ==== java-annoying-cla-shtuff: tried
[spray] [warn]   http://download.java.net/maven/2/com/decodified/scala-ssh_2.10/0.6.4/scala-ssh_2.10-0.6.4.pom
[spray] [warn] ==== typesafe-releases: tried
[spray] [warn]   http://typesafe.artifactoryonline.com/typesafe/releases/com/decodified/scala-ssh_2.10/0.6.4/scala-ssh_2.10-0.6.4.pom
[spray] [warn] ==== typesafe-ivy-releases: tried
[spray] [warn]   http://typesafe.artifactoryonline.com/typesafe/ivy-releases/com.decodified/scala-ssh_2.10/0.6.4/ivys/ivy.xml
[spray] [warn] ==== dbuild-snapshots: tried
[spray] [warn]   http://typesafe.artifactoryonline.com/typesafe/temp-distributed-build-snapshots/com.decodified/scala-ssh_2.10/0.6.4/ivys/ivy.xml
[spray] [warn] ==== sbt-plugin-releases: tried
[spray] [warn]   http://scalasbt.artifactoryonline.com/scalasbt/sbt-plugin-releases/com.decodified/scala-ssh_2.10/0.6.4/ivys/ivy.xml
[spray] [warn] ==== jgit-repo: tried
[spray] [warn]   http://download.eclipse.org/jgit/maven/com/decodified/scala-ssh_2.10/0.6.4/scala-ssh_2.10-0.6.4.pom
[spray] [warn] ==== scala-fresh-2.10.x: tried
[spray] [warn]   http://typesafe.artifactoryonline.com/typesafe/scala-fresh-2.10.x/com/decodified/scala-ssh_2.10/0.6.4/scala-ssh_2.10-0.6.4.pom
[spray] [warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[spray] [warn]  ::          UNRESOLVED DEPENDENCIES         ::
[spray] [warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[spray] [warn]  :: com.decodified#scala-ssh_2.10;0.6.4: not found
[spray] [warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[spray] sbt.ResolveException: unresolved dependency: com.decodified#scala-ssh_2.10;0.6.4: not found
[spray]         at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:217)
[spray]         at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:126)
[spray]         at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:125)
[spray]         at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:115)
[spray]         at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:115)
[spray]         at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:103)
[spray]         at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:48)
[spray]         at sbt.IvySbt$$anon$3.call(Ivy.scala:57)
[spray]         at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:98)
[spray]         at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:81)
[spray]         at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:102)
[spray]         at xsbt.boot.Using$.withResource(Using.scala:11)
[spray]         at xsbt.boot.Using$.apply(Using.scala:10)
[spray]         at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:62)
[spray]         at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:52)
[spray]         at xsbt.boot.Locks$.apply0(Locks.scala:31)
[spray]         at xsbt.boot.Locks$.apply(Locks.scala:28)
[spray]         at sbt.IvySbt.withDefaultLogger(Ivy.scala:57)
[spray]         at sbt.IvySbt.withIvy(Ivy.scala:98)
[spray]         at sbt.IvySbt.withIvy(Ivy.scala:94)
[spray]         at sbt.IvySbt$Module.withModule(Ivy.scala:115)
[spray]         at sbt.IvyActions$.update(IvyActions.scala:125)
[spray]         at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1223)
[spray]         at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1221)
[spray]         at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$74.apply(Defaults.scala:1244)
[spray]         at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$74.apply(Defaults.scala:1242)
[spray]         at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:35)
[spray]         at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1246)
[spray]         at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1241)
[spray]         at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:45)
[spray]         at sbt.Classpaths$.cachedUpdate(Defaults.scala:1249)
[spray]         at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1214)
[spray]         at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1192)
[spray]         at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[spray]         at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
[spray]         at sbt.std.Transform$$anon$4.work(System.scala:64)
[spray]         at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
[spray]         at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
[spray]         at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
[spray]         at sbt.Execute.work(Execute.scala:244)
[spray]         at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
[spray]         at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
[spray]         at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
[spray]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
[spray]         at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
[spray]         at java.util.concurrent.FutureTask.run(FutureTask.java:138)
[spray]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
[spray]         at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
[spray]         at java.util.concurrent.FutureTask.run(FutureTask.java:138)
[spray]         at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
[spray]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
[spray]         at java.lang.Thread.run(Thread.java:662)
[spray] [error] (*:update) sbt.ResolveException: unresolved dependency: com.decodified#scala-ssh_2.10;0.6.4: not found
[spray] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
[spray:error] java.lang.RuntimeException: 
[spray:error]   at scala.sys.package$.error(package.scala:27)
[spray:error]   at distributed.support.sbt.SbtRunner.distributed$support$sbt$SbtRunner$$processCommand(SbtRunner.scala:93)
[spray:error]   at distributed.support.sbt.SbtRunner$$anonfun$run$1$$anonfun$apply$2$$anonfun$apply$3.apply(SbtRunner.scala:74)
[spray:error]   at distributed.support.sbt.SbtRunner$$anonfun$run$1$$anonfun$apply$2$$anonfun$apply$3.apply(SbtRunner.scala:74)
[spray:error]   at distributed.support.sbt.SbtRunner$$anonfun$run$1.apply(SbtRunner.scala:74)
[spray:error]   at distributed.support.sbt.SbtRunner$$anonfun$run$1.apply(SbtRunner.scala:64)
[spray:error]   at sbt.IO$.withTemporaryFile(IO.scala:311)
[spray:error]   at distributed.support.sbt.SbtRunner.run(SbtRunner.scala:64)
[spray:error]   at distributed.support.sbt.SbtExtractor$.extractMetaData(DependencyExtractor.scala:99)
[spray:error]   at distributed.support.sbt.SbtBuildSystem.extractDependencies(SbtBuildSystem.scala:58)
[spray:error]   at distributed.support.sbt.SbtBuildSystem.extractDependencies(SbtBuildSystem.scala:18)
[spray] --== End Extracting dependencies for spray ==--
```
Do I have to something special to solve this?

**Comment by SethTisue** [comment]
closing on the assumption that lots has changed since the initial report. we can reopen if it rears its head again.

running the full community build locally is generally not recommended since it takes forever because you won't benefit from the caching the real Jenkins jobs on scala-ci have. if you have a branch with changes to the community build config you want to test, let us know, we can run them on Jenkins for you.
