### ISSUE TITLE
weird FastTypeTag errors started recently

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#806]
```
unexpected FAILED: nyaya
	scala.MatchError: FastTypeTag[sbt.CrossVersion] (of class scala.pickling.FastTypeTag$$anon$2)
unexpected FAILED: ssl-config
	[ssl-config] scala.MatchError: FastTypeTag[sbt.CrossVersion] (of class scala.pickling.FastTypeTag$$anon$2)
```

@eed3si9n @cunei does the error message give you any immediate insight into what might be going on here? I would have to isolate whether it started with the sbt 1.2.6 upgrade, or the dbuild 0.9.16 upgrade, or what. I could also try to figure out what's special about these two projects.

I have now seen this both on MacOS (my laptop) and Linux (Jenkins), on these two projects in particular. 

don't go digging yet, for now I just want to know whether the error message alone rings any bells.

**Comment by cunei** [comment]
The dbuild 0.9.16 upgrade may not be the cause: the change with respect to 0.9.15 is quite modest. It adds one additional dependency, but it is a simple java library that has [no other dependencies](http://central.maven.org/maven2/org/apache/servicemix/bundles/org.apache.servicemix.bundles.oro/2.0.8_6/org.apache.servicemix.bundles.oro-2.0.8_6.pom), so unlikely to have this effect.

**Comment by SethTisue** [comment]
I don't know but maybe 0e619c1c2de97803b5bc5b8549ecf8a57e97a36c will help

**Comment by SethTisue** [comment]
a full stack trace:

```
[ssl-config] scala.MatchError: FastTypeTag[sbt.CrossVersion] (of class scala.pickling.FastTypeTag$$anon$2)
[ssl-config] 	at sbt.CrossVersion$$anon$2.unpickle(CrossVersion.scala:67)
[ssl-config] 	at sbt.ModuleID$SbtModuleIDPicklerUnpickler1$2$.unpickle(ModuleID.scala:167)
[ssl-config] 	at sbt.ModuleReport$SbtModuleReportPicklerUnpickler1$2$.unpickle(UpdateReport.scala:168)
[ssl-config] 	at scala.pickling.Unpickler$class.unpickleEntry(Pickler.scala:79)
[ssl-config] 	at sbt.ModuleReport$SbtModuleReportPicklerUnpickler1$2$.unpickleEntry(UpdateReport.scala:168)
[ssl-config] 	at sbt.serialization.pickler.TravPickler$$anon$1.unpickle(Traversable.scala:89)
[ssl-config] 	at sbt.OrganizationArtifactReport$SbtOrganizationArtifactReportPicklerUnpickler1$2$.unpickle(UpdateReport.scala:71)
[ssl-config] 	at scala.pickling.Unpickler$class.unpickleEntry(Pickler.scala:79)
[ssl-config] 	at sbt.OrganizationArtifactReport$SbtOrganizationArtifactReportPicklerUnpickler1$2$.unpickleEntry(UpdateReport.scala:71)
[ssl-config] 	at sbt.serialization.pickler.TravPickler$$anon$1.unpickle(Traversable.scala:89)
[ssl-config] 	at sbt.ConfigurationReportLite$SbtConfigurationReportLitePicklerUnpickler1$2$.unpickle(JsonUtil.scala:87)
[ssl-config] 	at scala.pickling.Unpickler$class.unpickleEntry(Pickler.scala:79)
[ssl-config] 	at sbt.ConfigurationReportLite$SbtConfigurationReportLitePicklerUnpickler1$2$.unpickleEntry(JsonUtil.scala:87)
[ssl-config] 	at sbt.serialization.pickler.TravPickler$$anon$1.unpickle(Traversable.scala:89)
[ssl-config] 	at sbt.UpdateReportLite$SbtUpdateReportLitePicklerUnpickler1$2$.unpickle(JsonUtil.scala:82)
[ssl-config] 	at scala.pickling.Unpickler$class.unpickleEntry(Pickler.scala:79)
[ssl-config] 	at sbt.UpdateReportLite$SbtUpdateReportLitePicklerUnpickler1$2$.unpickleEntry(JsonUtil.scala:82)
[ssl-config] 	at scala.pickling.functions$.unpickle(functions.scala:11)
[ssl-config] 	at sbt.serialization.JsonValue$$anonfun$parse$1.apply(SerializedValue.scala:108)
[ssl-config] 	at scala.util.Try$.apply(Try.scala:161)
[ssl-config] 	at sbt.serialization.JsonValue.parse(SerializedValue.scala:108)
[ssl-config] 	at sbt.serialization.SerializationFunctions$class.fromJsonFile(SerializationFunctions.scala:18)
[ssl-config] 	at sbt.serialization.package$.fromJsonFile(package.scala:9)
[ssl-config] 	at sbt.JsonUtil$.parseUpdateReport(JsonUtil.scala:17)
[ssl-config] 	at sbt.ivyint.CachedResolutionResolveCache.sbt$ivyint$CachedResolutionResolveCache$$loadMiniGraphFromFile$1(CachedResolutionResolveEngine.scala:165)
[ssl-config] 	at sbt.ivyint.CachedResolutionResolveCache$$anonfun$7.apply(CachedResolutionResolveEngine.scala:176)
[ssl-config] 	at sbt.ivyint.CachedResolutionResolveCache$$anonfun$7.apply(CachedResolutionResolveEngine.scala:176)
[ssl-config] 	at scala.Option.orElse(Option.scala:257)
[ssl-config] 	at sbt.ivyint.CachedResolutionResolveCache.getOrElseUpdateMiniGraph(CachedResolutionResolveEngine.scala:176)
[ssl-config] 	at sbt.ivyint.CachedResolutionResolveEngine$$anonfun$customResolve$1$$anonfun$17.apply(CachedResolutionResolveEngine.scala:363)
[ssl-config] 	at sbt.ivyint.CachedResolutionResolveEngine$$anonfun$customResolve$1$$anonfun$17.apply(CachedResolutionResolveEngine.scala:337)
[ssl-config] 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
[ssl-config] 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
[ssl-config] 	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
[ssl-config] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
[ssl-config] 	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
[ssl-config] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[ssl-config] 	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
[ssl-config] 	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
[ssl-config] 	at sbt.ivyint.CachedResolutionResolveEngine$$anonfun$customResolve$1.apply(CachedResolutionResolveEngine.scala:337)
[ssl-config] 	at sbt.ivyint.CachedResolutionResolveEngine$$anonfun$customResolve$1.apply(CachedResolutionResolveEngine.scala:286)
[ssl-config] 	at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:189)
[ssl-config] 	at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:632)
[ssl-config] 	at sbt.ivyint.CachedResolutionResolveCache.getOrElseUpdateProjectReport(CachedResolutionResolveEngine.scala:244)
[ssl-config] 	at sbt.ivyint.CachedResolutionResolveEngine$class.customResolve(CachedResolutionResolveEngine.scala:286)
[ssl-config] 	at sbt.IvySbt$$anon$5$$anon$3.customResolve(Ivy.scala:102)
[ssl-config] 	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:178)
[ssl-config] 	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
[ssl-config] 	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
[ssl-config] 	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
[ssl-config] 	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:133)
[ssl-config] 	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
[ssl-config] 	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
[ssl-config] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
[ssl-config] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
[ssl-config] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
[ssl-config] 	at xsbt.boot.Using$.withResource(Using.scala:10)
[ssl-config] 	at xsbt.boot.Using$.apply(Using.scala:9)
[ssl-config] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
[ssl-config] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
[ssl-config] 	at xsbt.boot.Locks$.apply0(Locks.scala:31)
[ssl-config] 	at xsbt.boot.Locks$.apply(Locks.scala:28)
[ssl-config] 	at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
[ssl-config] 	at sbt.IvySbt.withIvy(Ivy.scala:128)
[ssl-config] 	at sbt.IvySbt.withIvy(Ivy.scala:125)
[ssl-config] 	at sbt.IvySbt$Module.withModule(Ivy.scala:156)
[ssl-config] 	at sbt.IvyActions$.updateEither(IvyActions.scala:168)
[ssl-config] 	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1555)
[ssl-config] 	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1551)
[ssl-config] 	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$122.apply(Defaults.scala:1586)
[ssl-config] 	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$122.apply(Defaults.scala:1584)
[ssl-config] 	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
[ssl-config] 	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1589)
[ssl-config] 	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1583)
[ssl-config] 	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
[ssl-config] 	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1606)
[ssl-config] 	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1533)
[ssl-config] 	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1485)
[ssl-config] 	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[ssl-config] 	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
[ssl-config] 	at sbt.std.Transform$$anon$4.work(System.scala:63)
[ssl-config] 	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[ssl-config] 	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[ssl-config] 	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[ssl-config] 	at sbt.Execute.work(Execute.scala:237)
[ssl-config] 	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[ssl-config] 	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[ssl-config] 	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
[ssl-config] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[ssl-config] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[ssl-config] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[ssl-config] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[ssl-config] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[ssl-config] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[ssl-config] 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by SethTisue** [comment]
@eed3si9n I see stuff about cached resolution in the stack trace, perhaps this has to do with the cached resolution changes in sbt 1.2.6?

**Comment by SethTisue** [comment]
gah, or not, actually both projects are on 0.13.7

**Comment by SethTisue** [comment]
ah, but maybe it's a clue regardless. both projects use `withCachedResolution(true)`. they aren't the only two projects to use it, but it isn't a super common thing to have enabled, either

**Comment by eed3si9n** [comment]
I see Scala Pickling in the stack trace so that probably something specific to sbt 0.13.
I'd recommend we try upgrading the build to use sbt 1.

**Comment by eed3si9n** [comment]
Looks like HEAD is already at sbt 1 https://github.com/lightbend/ssl-config/blob/f417509e22006baba2a00d42481120b81ad972cd/project/build.properties but it was frozen in August https://github.com/scala/community-builds/commit/3514a6ce32d39417635320c19b1c9a03d2c786f0.

**Comment by SethTisue** [comment]
> I'd recommend we try upgrading the build to use sbt 1

okay, that's doable, and it's desirable anyway, I'll try that path

**Comment by SethTisue** [comment]
@japgolly perhaps you've been meaning to move nyaya to sbt 1 anyway...?

**Comment by SethTisue** [comment]
at #808 I'm attempting to bring in ssl-config's sbt 1 upgrade

**Comment by japgolly** [comment]
Hi. Yeah no problem, I'm happy to upgrade to new SBT but I won't have much
computer time until next week. I hope this isn't urgent...?

**Comment by SethTisue** [comment]
@japgolly definitely not urgent

**Comment by SethTisue** [comment]
nyaya is on sbt 1 now and I haven't seen this error on any other projects in the last couple months
