### ISSUE TITLE
regression: enumeratum failing (2.12.x)

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#807]
lloydmeta/enumeratum@8a23bbd2a8467fd9141ac348c8065d95ae5bcf9a was green at https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3663/

subsequent runs have been red, since lloydmeta/enumeratum@e8ded23f78038f3a1bde1577b6aa6e3f9010232f (a few more build tweaks were made sense then)

/cc @lloydmeta

**Comment by SethTisue** [comment]
the stack trace is

```
[enumeratum] ----------------------
[enumeratum] Processing subproject: coreJVMTests
[enumeratum] All Dependencies for subproject coreJVMTests:
[enumeratum]    org.scala-lang:scala-compiler:2.12.8-bin-6914d3b:scala-tool->default,optional(default)
[enumeratum]    org.scala-lang:scala-library:2.12.8-bin-6914d3b:scala-tool->default,optional(default)
[enumeratum]    com.beachape:enumeratum:0.1.0-dbuildx8eb83d65bfe446ec47c2f2157a99f81954a73725
[enumeratum]    com.beachape:enumeratum-macros:0.1.0-dbuildx8eb83d65bfe446ec47c2f2157a99f81954a73725
[enumeratum]    com.lightbend:cloc-plugin:0.0.1-dbuildxfbec55f5bd9e5227837214dad4897c1fba9b3cc1:plugin->default(compile)
[enumeratum]    org.scala-lang:scala-library:2.12.8-bin-6914d3b
[enumeratum]    org.wartremover:wartremover:2.3.8-dbuildxe3f0530fa77b56b35b96ad3de70f687ac63848c1:plugin->default(compile)
[enumeratum]    org.scalatest:scalatest:3.0.6-dbuildx2f27aeed286ee556e5d4cb78a1ca5de0645026c7:test
[enumeratum]    org.scala-lang:scala-compiler:2.12.8-bin-6914d3b:test
[enumeratum] Running build: coreJVMTests
[enumeratum] Running "test" in: coreJVMTests
[enumeratum] [info] Updating coreJVMTests...
[enumeratum] [info] Done updating.
[enumeratum] [error] Modules were resolved with conflicting cross-version suffixes in ProjectRef(uri("file:/home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.16/project-builds/enumeratum-8eb83d65bfe446ec47c2f2157a99f81954a73725/"), "coreJVMTests"):
[enumeratum] [error]    com.beachape:enumeratum-macros _2.12, <none>
[enumeratum] [error] java.lang.RuntimeException: Conflicting cross-version suffixes in: com.beachape:enumeratum-macros
[enumeratum] [error] 	at scala.sys.package$.error(package.scala:26)
[enumeratum] [error] 	at sbt.librarymanagement.ConflictWarning$.processCrossVersioned(ConflictWarning.scala:39)
[enumeratum] [error] 	at sbt.librarymanagement.ConflictWarning$.apply(ConflictWarning.scala:19)
[enumeratum] [error] 	at sbt.Classpaths$.$anonfun$ivyBaseSettings$63(Defaults.scala:2139)
[enumeratum] [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[enumeratum] [error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[enumeratum] [error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[enumeratum] [error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[enumeratum] [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[enumeratum] [error] 	at sbt.Execute.work(Execute.scala:278)
[enumeratum] [error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[enumeratum] [error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[enumeratum] [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[enumeratum] [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[enumeratum] [error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[enumeratum] [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[enumeratum] [error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[enumeratum] [error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[enumeratum] [error] 	at java.lang.Thread.run(Thread.java:748)
[enumeratum] [error] (coreJVMTests / update) Conflicting cross-version suffixes in: com.beachape:enumeratum-macros
```

**Comment by SethTisue** [comment]
I don't know why this is about... some guesses:

* wartremover-related?
* related to  `version := Versions.Macros.head`?
* related to `crossScalaVersions := scalaVersionsAll`?
* related to `.crossType(CrossType.Pure)`?

**Comment by SethTisue** [comment]
maybe we can just sweep it under the rug with `set every conflictWarning := ConflictWarning.disable`. trying that at https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3672/

**Comment by SethTisue** [comment]
that lump under the rug? oh, it's nothing
