### ISSUE TITLE
classutil fails to extract on JDK 11

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#809]
https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-jdk11-integrate-community-build/133/

coursier-related, fastparse-related. I should see if moving to a newer coursier fixes it, otherwise see if the problem is reproducible and report it upstream (to Brian and/or Alex)

```
[classutil] [error] java.lang.IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class coursier/shaded/fastparse/core/LowestPriSequencer. Method $anonfun$Sequencer1$1(Ljava/lang/Object;Ljava/lang/Object;)Lscala/Tuple2; at index 39 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef
[classutil] [error] 	at coursier.shaded.fastparse.core.LowestPriSequencer.Sequencer1(SequencerGen.scala:88)
[classutil] [error] 	at coursier.shaded.fastparse.core.LowestPriSequencer.Sequencer1$(SequencerGen.scala:88)
[classutil] [error] 	at coursier.shaded.fastparse.core.Implicits$Sequencer$.Sequencer1(Implicits.scala:16)
[classutil] [error] 	at coursier.ivy.PropertiesPattern$.$anonfun$parser$6(Pattern.scala:132)
[classutil] [error] 	at coursier.shaded.fastparse.parsers.Combinators$Rule.pCached$lzycompute(Combinators.scala:155)
[classutil] [error] 	at coursier.shaded.fastparse.parsers.Combinators$Rule.pCached(Combinators.scala:155)
[classutil] [error] 	at coursier.shaded.fastparse.parsers.Combinators$Rule.parseRec(Combinators.scala:160)
[classutil] [error] 	at coursier.shaded.fastparse.parsers.Transformers$Mapper.parseRec(Transformers.scala:19)
[classutil] [error] 	at coursier.shaded.fastparse.parsers.Combinators$Either.rec$4(Combinators.scala:528)
[classutil] [error] 	at coursier.shaded.fastparse.parsers.Combinators$Either.parseRec(Combinators.scala:544)
[classutil] [error] 	at coursier.shaded.fastparse.parsers.Combinators$Repeat.rec$3(Combinators.scala:452)
[classutil] [error] 	at coursier.shaded.fastparse.parsers.Combinators$Repeat.parseRec(Combinators.scala:489)
[classutil] [error] 	at coursier.shaded.fastparse.parsers.Combinators$Rule.parseRec(Combinators.scala:160)
[classutil] [error] 	at coursier.shaded.fastparse.parsers.Transformers$Mapper.parseRec(Transformers.scala:19)
[classutil] [error] 	at coursier.shaded.fastparse.core.Parser.parseInput(Parsing.scala:376)
[classutil] [error] 	at coursier.shaded.fastparse.core.Parser.parse(Parsing.scala:358)
[classutil] [error] 	at coursier.ivy.PropertiesPattern$.parse(Pattern.scala:148)
[classutil] [error] 	at coursier.Tasks$.$anonfun$exceptionPatternParser$2(Tasks.scala:452)
[classutil] [error] 	at coursier.CoursierPlugin$.<init>(CoursierPlugin.scala:149)
[classutil] [error] 	at coursier.CoursierPlugin$.<clinit>(CoursierPlugin.scala)
[classutil] [error] 	at java.base/java.lang.Class.forName0(Native Method)
[classutil] [error] 	at java.base/java.lang.Class.forName(Class.java:398)
[classutil] [error] 	at sbt.internal.inc.ModuleUtilities$.getObject(ModuleUtilities.scala:20)
[classutil] [error] 	at sbt.internal.inc.ModuleUtilities$.getCheckedObject(ModuleUtilities.scala:27)
[classutil] [error] 	at sbt.internal.inc.ModuleUtilities$.$anonfun$getCheckedObjects$1(ModuleUtilities.scala:31)
[classutil] [error] 	at scala.collection.immutable.Stream.$anonfun$map$1(Stream.scala:414)
[classutil] [error] 	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1167)
[classutil] [error] 	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1157)
[classutil] [error] 	at scala.collection.generic.Growable.loop$1(Growable.scala:53)
[classutil] [error] 	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:57)
[classutil] [error] 	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:49)
[classutil] [error] 	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:185)
[classutil] [error] 	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:43)
[classutil] [error] 	at scala.collection.TraversableLike.$plus$plus(TraversableLike.scala:146)
[classutil] [error] 	at scala.collection.TraversableLike.$plus$plus$(TraversableLike.scala:142)
[classutil] [error] 	at scala.collection.immutable.List.$plus$plus(List.scala:206)
[classutil] [error] 	at sbt.internal.PluginDiscovery$.discoverAll(PluginDiscovery.scala:56)
[classutil] [error] 	at sbt.internal.Load$.loadPlugins(Load.scala:1318)
[classutil] [error] 	at sbt.internal.Load$.loadPluginDefinition(Load.scala:1263)
[classutil] [error] 	at sbt.internal.Load$.buildPlugins(Load.scala:1242)
[classutil] [error] 	at sbt.internal.Load$.plugins(Load.scala:1225)
[classutil] [error] 	at sbt.internal.Load$.$anonfun$loadUnit$2(Load.scala:694)
[classutil] [error] 	at sbt.internal.Load$.timed(Load.scala:1395)
[classutil] [error] 	at sbt.internal.Load$.$anonfun$loadUnit$1(Load.scala:694)
[classutil] [error] 	at sbt.internal.Load$.timed(Load.scala:1395)
[classutil] [error] 	at sbt.internal.Load$.loadUnit(Load.scala:688)
[classutil] [error] 	at sbt.internal.Load$.$anonfun$builtinLoader$4(Load.scala:484)
[classutil] [error] 	at sbt.internal.BuildLoader$.$anonfun$componentLoader$5(BuildLoader.scala:176)
[classutil] [error] 	at sbt.internal.BuildLoader.apply(BuildLoader.scala:241)
[classutil] [error] 	at sbt.internal.Load$.loadURI$1(Load.scala:546)
[classutil] [error] 	at sbt.internal.Load$.loadAll(Load.scala:562)
[classutil] [error] 	at sbt.internal.Load$.loadURI(Load.scala:492)
[classutil] [error] 	at sbt.internal.Load$.load(Load.scala:471)
[classutil] [error] 	at sbt.internal.Load$.$anonfun$apply$1(Load.scala:251)
[classutil] [error] 	at sbt.internal.Load$.timed(Load.scala:1395)
[classutil] [error] 	at sbt.internal.Load$.apply(Load.scala:251)
[classutil] [error] 	at sbt.internal.Load$.defaultLoad(Load.scala:69)
[classutil] [error] 	at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:829)
[classutil] [error] 	at sbt.BuiltinCommands$.doLoadProject(Main.scala:829)
[classutil] [error] 	at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:800)
[classutil] [error] 	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:142)
[classutil] [error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:137)
[classutil] [error] 	at sbt.Command$.process(Command.scala:181)
[classutil] [error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:151)
[classutil] [error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:139)
[classutil] [error] 	at sbt.State$$anon$1.runCmd$1(State.scala:246)
[classutil] [error] 	at sbt.State$$anon$1.process(State.scala:250)
[classutil] [error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:139)
[classutil] [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[classutil] [error] 	at sbt.MainLoop$.next(MainLoop.scala:139)
[classutil] [error] 	at sbt.MainLoop$.run(MainLoop.scala:132)
[classutil] [error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:110)
[classutil] [error] 	at sbt.io.Using.apply(Using.scala:22)
[classutil] [error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:104)
[classutil] [error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:59)
[classutil] [error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:44)
[classutil] [error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:35)
[classutil] [error] 	at sbt.StandardMain$.runManaged(Main.scala:138)
[classutil] [error] 	at sbt.xMain.run(Main.scala:89)
[classutil] [error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[classutil] [error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[classutil] [error] 	at xsbt.boot.Launch$.run(Launch.scala:109)
[classutil] [error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[classutil] [error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)
[classutil] [error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)
[classutil] [error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
[classutil] [error] 	at xsbt.boot.Boot$.main(Boot.scala:17)
[classutil] [error] 	at xsbt.boot.Boot.main(Boot.scala)
[classutil] [error] java.lang.IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class coursier/shaded/fastparse/core/LowestPriSequencer. Method $anonfun$Sequencer1$1(Ljava/lang/Object;Ljava/lang/Object;)Lscala/Tuple2; at index 39 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef
[classutil] [error] Use 'last' for the full log.
[classutil] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
[classutil:error] java.lang.RuntimeException: 
[classutil:error] 	at scala.sys.package$.error(package.scala:27)
[classutil:error] 	at com.typesafe.dbuild.support.sbt.SbtRunner.com$typesafe$dbuild$support$sbt$SbtRunner$$processCommand(SbtRunner.scala:94)
[classutil:error] 	at com.typesafe.dbuild.support.sbt.SbtRunner$$anonfun$run$1$$anonfun$apply$2$$anonfun$apply$3.apply(SbtRunner.scala:75)
[classutil:error] 	at com.typesafe.dbuild.support.sbt.SbtRunner$$anonfun$run$1$$anonfun$apply$2$$anonfun$apply$3.apply(SbtRunner.scala:75)
[classutil:error] 	at com.typesafe.dbuild.support.sbt.SbtRunner$$anonfun$run$1.apply(SbtRunner.scala:75)
[classutil:error] 	at com.typesafe.dbuild.support.sbt.SbtRunner$$anonfun$run$1.apply(SbtRunner.scala:66)
[classutil:error] 	at sbt.IO$.withTemporaryFile(IO.scala:389)
[classutil:error] 	at com.typesafe.dbuild.support.sbt.SbtRunner.run(SbtRunner.scala:66)
[classutil:error] 	at com.typesafe.dbuild.support.sbt.SbtExtractor$.extractMetaData(DependencyExtractor.scala:107)
[classutil:error] 	at com.typesafe.dbuild.support.sbt.SbtBuildSystem.extractDependencies(SbtBuildSystem.scala:85)
[classutil:error] 	at com.typesafe.dbuild.support.sbt.SbtBuildSystem.extractDependencies(SbtBuildSystem.scala:22)
```

/cc @bmc

**Comment by SethTisue** [comment]
oh, it's https://github.com/coursier/coursier/pull/678, so it looks like a coursier version bump in classutil would take care of it

**Comment by SethTisue** [comment]
8089afd8d5d3221fb8b2405d22e3aeb9ef6720c6, https://github.com/bmc/classutil/pull/32
