### ISSUE TITLE
2.13 simulacrum sbt-gpg

### ISSUE THREAD

**Issue by ashawley** [scala/community-builds#816]
Yesterday, the project switched from sbt-pgp to sbt-gpg:

mpilquist/simulacrum@bdf9268a6bb0373149dff225a1e45ce26ad72eea

```
[info] gpg: no default secret key: No secret key
[info] gpg: signing failed: No secret key
[error] java.lang.RuntimeException: GPG reported an error. Artifacts won't be signed.
[error] 	at scala.sys.package$.error(package.scala:26)
[error] 	at io.crashbox.gpg.SbtGpg$.$anonfun$packagedArtifactsImpl$2(SbtGpg.scala:45)
[error] 	at io.crashbox.gpg.SbtGpg$.$anonfun$packagedArtifactsImpl$1(SbtGpg.scala:47)
[error] 	at scala.collection.TraversableOnce.$anonfun$foldLeft$1(TraversableOnce.scala:156)
[error] 	at scala.collection.TraversableOnce.$anonfun$foldLeft$1$adapted(TraversableOnce.scala:156)
[error] 	at scala.collection.immutable.Map$Map4.foreach(Map.scala:233)
[error] 	at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:156)
[error] 	at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:154)
[error] 	at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
[error] 	at io.crashbox.gpg.SbtGpg$.packagedArtifactsImpl(SbtGpg.scala:37)
[error] 	at io.crashbox.gpg.SbtGpg$.$anonfun$signingSettings$1(SbtGpg.scala:78)
[error] (coreJVM / publish / packagedArtifacts) GPG reported an error. Artifacts won't be signed.
```

**Comment by SethTisue** [comment]
fixed: d7e0afb
