### ISSUE TITLE
move to sbt 1.3.x when we can

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#918]
for a while we were using 1.3.0-RC1 for most projects (#909), but Adriaan reverted the change because he was seeing intermittent errors during extraction

it can wait until after 2.13.0 is out, but we should try again, perhaps once there's an 1.3.0- RC2

/cc @eed3si9n

**Comment by SethTisue** [comment]
@adriaanm what kinds of problem did you see? did it look like https://github.com/sbt/sbt/issues/4723 , or was it something else?

**Comment by adriaanm** [comment]
In https://scala-ci.typesafe.com/view/scala-2.11.x/job/scala-2.11.x-jdk11-integrate-community-build/58/consoleFull

```
[mima] [error] /home/jenkins/workspace/scala-2.11.x-jdk11-integrate-community-build/target-0.9.16/extraction/0e8052dfc53d3f27bb2826ce3186554330ec3740/projects/e6685b53cfec16dc351a46e54b9ebc48f3dd59e6/project/Build.scala:277:32: method newInstance in class Class is deprecated: see corresponding Javadoc for more information.
[mima] [error]     val testRunner = testClass.newInstance().asInstanceOf[ {
[mima] [error]                                ^
[mima] [error] one error found
[mima] [error] (Compile / compileIncremental) Compilation failed
[mima] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
```

mima hadn't moved in a while, so i suspect sbt

**Comment by adriaanm** [comment]
And also at  https://scala-ci.typesafe.com/view/scala-2.11.x/job/scala-2.11.x-jdk11-integrate-community-build/60/consoleFull

```
[scala-swing] Using Scala 2.11.12-bin-efd31ff during extraction.
[scala-swing] Using sbt version: 1.3.0-RC1
[scala-swing:error] OpenJDK 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
[scala-swing:error] Exception in thread "sbt-load-global-instance" java.lang.ExceptionInInitializerError
[scala-swing:error] 	at com.swoval.files.DirectoryListers.init(DirectoryListers.java:29)
[scala-swing:error] 	at com.swoval.files.FileTreeViews.<clinit>(FileTreeViews.java:21)
[scala-swing:error] 	at sbt.nio.file.FileTreeView$DefaultFileTreeView$.<init>(FileTreeView.scala:44)
[scala-swing:error] 	at sbt.nio.file.FileTreeView$DefaultFileTreeView$.<clinit>(FileTreeView.scala)
[scala-swing:error] 	at sbt.nio.file.FileTreeView$.<init>(FileTreeView.scala:82)
[scala-swing:error] 	at sbt.nio.file.FileTreeView$.<clinit>(FileTreeView.scala)
[scala-swing:error] 	at sbt.io.Path$.<init>(Path.scala:318)
[scala-swing:error] 	at sbt.io.Path$.<clinit>(Path.scala)
[scala-swing:error] 	at sbt.internal.parser.SbtParser$.<init>(SbtParser.scala:45)
[scala-swing:error] 	at sbt.internal.parser.SbtParser$.<clinit>(SbtParser.scala)
[scala-swing:error] 	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
[scala-swing:error] 	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1042)
[scala-swing:error] 	at java.base/jdk.internal.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
[scala-swing:error] 	at java.base/jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:186)
[scala-swing:error] 	at java.base/java.lang.reflect.Field.acquireFieldAccessor(Field.java:1105)
[scala-swing:error] 	at java.base/java.lang.reflect.Field.getFieldAccessor(Field.java:1086)
[scala-swing:error] 	at java.base/java.lang.reflect.Field.get(Field.java:418)
[scala-swing:error] 	at sbt.xMain$$anon$1.run(Main.scala:51)
[scala-swing:error] Caused by: java.lang.RuntimeException: java.nio.file.NoSuchFileException: /tmp/swoval-jni/16934016062546041395-libswoval-files0.so
[scala-swing:error] 	at com.swoval.files.NativeDirectoryLister.<clinit>(NativeDirectoryLister.java:34)
[scala-swing:error] 	... 18 more
[scala-swing:error] Caused by: java.nio.file.NoSuchFileException: /tmp/swoval-jni/16934016062546041395-libswoval-files0.so
[scala-swing:error] 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
[scala-swing:error] 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
[scala-swing:error] 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
[scala-swing:error] 	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:215)
[scala-swing:error] 	at java.base/java.nio.file.Files.newByteChannel(Files.java:370)
[scala-swing:error] 	at java.base/java.nio.file.Files.createFile(Files.java:647)
[scala-swing:error] 	at java.base/java.nio.file.TempFileHelper.create(TempFileHelper.java:137)
[scala-swing:error] 	at java.base/java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:160)
[scala-swing:error] 	at java.base/java.nio.file.Files.createTempFile(Files.java:867)
[scala-swing:error] 	at com.swoval.runtime.NativeLoader.loadPackaged(NativeLoader.java:117)
[scala-swing:error] 	at com.swoval.runtime.NativeLoader.loadPackaged(NativeLoader.java:169)
[scala-swing:error] 	at com.swoval.files.NativeDirectoryLister.<clinit>(NativeDirectoryLister.java:32)
[scala-swing:error] 	... 18 more
[scala-swing] [error] java.lang.NoClassDefFoundError: Could not initialize class sbt.io.Path$
[scala-swing] [error] 	at sbt.internal.CommandStrings$.sbtRCs(CommandStrings.scala:341)
[scala-swing] [error] 	at sbt.BuiltinCommands$.$anonfun$initialize$1(Main.scala:476)
[scala-swing] [error] 	at sbt.Command$.$anonfun$command$2(Command.scala:93)
[scala-swing] [error] 	at sbt.Command$.process(Command.scala:183)
[scala-swing] [error] 	at sbt.MainLoop$.$anonfun$processCommand$1(MainLoop.scala:150)
[scala-swing] [error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:162)
[scala-swing] [error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:150)
[scala-swing] [error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:138)
[scala-swing] [error] 	at sbt.State$StateOpsImpl$.runCmd$1(State.scala:269)
[scala-swing] [error] 	at sbt.State$StateOpsImpl$.process$extension(State.scala:273)
[scala-swing] [error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:138)
[scala-swing] [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[scala-swing] [error] 	at sbt.MainLoop$.next(MainLoop.scala:138)
[scala-swing] [error] 	at sbt.MainLoop$.run(MainLoop.scala:131)
[scala-swing] [error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:109)
[scala-swing] [error] 	at sbt.io.Using.apply(Using.scala:27)
[scala-swing] [error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:103)
[scala-swing] [error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:58)
[scala-swing] [error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:43)
[scala-swing] [error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:34)
[scala-swing] [error] 	at sbt.StandardMain$.runManaged(Main.scala:173)
[scala-swing] [error] 	at sbt.xMainImpl$.run(Main.scala:126)
[scala-swing] [error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[scala-swing] [error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[scala-swing] [error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[scala-swing] [error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[scala-swing] [error] 	at sbt.xMain.run(Main.scala:55)
[scala-swing] [error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[scala-swing] [error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[scala-swing] [error] 	at xsbt.boot.Launch$.run(Launch.scala:109)
[scala-swing] [error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[scala-swing] [error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)
[scala-swing] [error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)
[scala-swing] [error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
[scala-swing] [error] 	at xsbt.boot.Boot$.main(Boot.scala:17)
[scala-swing] [error] 	at xsbt.boot.Boot.main(Boot.scala)
[scala-swing] [error] java.lang.NoClassDefFoundError: Could not initialize class sbt.io.Path$
[scala-swing] [error] Use 'last' for the full log.
[scala-swing:error] java.lang.NoClassDefFoundError: Could not initialize class sbt.nio.file.FileTreeView$
[scala-swing:error] 	at sbt.io.IO$.$anonfun$delete$2(IO.scala:583)
[scala-swing:error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[scala-swing:error] 	at sbt.internal.io.Retry$.liftedTree2$1(Retry.scala:38)
[scala-swing:error] 	at sbt.internal.io.Retry$.impl$1(Retry.scala:38)
[scala-swing:error] 	at sbt.internal.io.Retry$.apply(Retry.scala:52)
[scala-swing:error] 	at sbt.internal.io.Retry$.apply(Retry.scala:24)
[scala-swing:error] 	at sbt.io.IO$.delete(IO.scala:581)
[scala-swing:error] 	at sbt.internal.AbstractBackgroundJobService.shutdown(DefaultBackgroundJobService.scala:153)
[scala-swing:error] 	at sbt.StandardMain$.runManaged(Main.scala:178)
[scala-swing:error] 	at sbt.xMainImpl$.run(Main.scala:126)
[scala-swing:error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[scala-swing:error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[scala-swing:error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[scala-swing:error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[scala-swing:error] 	at sbt.xMain.run(Main.scala:55)
[scala-swing:error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[scala-swing:error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[scala-swing:error] 	at xsbt.boot.Launch$.run(Launch.scala:109)
[scala-swing:error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[scala-swing:error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)
[scala-swing:error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)
[scala-swing:error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
[scala-swing:error] 	at xsbt.boot.Boot$.main(Boot.scala:17)
[scala-swing:error] 	at xsbt.boot.Boot.main(Boot.scala)
[scala-swing] Error during sbt execution: java.lang.NoClassDefFoundError: Could not initialize class sbt.nio.file.FileTreeView$
[scala-swing:error] java.lang.RuntimeException: 
[scala-swing:error] 	at scala.sys.package$.error(package.scala:27)
[scala-swing:error] 	at com.typesafe.dbuild.support.sbt.SbtRunner.com$typesafe$dbuild$support$sbt$SbtRunner$$processCommand(SbtRunner.scala:94)
[scala-swing:error] 	at com.typesafe.dbuild.support.sbt.SbtRunner$$anonfun$run$1$$anonfun$apply$2$$anonfun$apply$3.apply(SbtRunner.scala:75)
[scala-swing:error] 	at com.typesafe.dbuild.support.sbt.SbtRunner$$anonfun$run$1$$anonfun$apply$2$$anonfun$apply$3.apply(SbtRunner.scala:75)
[scala-swing:error] 	at com.typesafe.dbuild.support.sbt.SbtRunner$$anonfun$run$1.apply(SbtRunner.scala:75)
[scala-swing:error] 	at com.typesafe.dbuild.support.sbt.SbtRunner$$anonfun$run$1.apply(SbtRunner.scala:66)
[scala-swing:error] 	at sbt.IO$.withTemporaryFile(IO.scala:389)
[scala-swing:error] 	at com.typesafe.dbuild.support.sbt.SbtRunner.run(SbtRunner.scala:66)
[scala-swing:error] 	at com.typesafe.dbuild.support.sbt.SbtExtractor$.extractMetaData(DependencyExtractor.scala:107)
[scala-swing:error] 	at com.typesafe.dbuild.support.sbt.SbtBuildSystem.extractDependencies(SbtBuildSystem.scala:85)
[scala-swing:error] 	at com.typesafe.dbuild.support.sbt.SbtBuildSystem.extractDependencies(SbtBuildSystem.scala:22)
```

**Comment by adriaanm** [comment]
https://scala-ci.typesafe.com/job/scala-2.11.x-jdk11-integrate-community-build/62/console should tell us whether going back to 1.2.8 fixed it, or whether it's the changes in 2.11.x

**Comment by SethTisue** [comment]
the MiMa one is because `Class.newInstance` is deprecated in JDK 11. it should go away if we switch off `-Xfatal-warnings` (either for that repo only, or build-wide; the 2.13 build has it switched off build-wide, but the 2.12 & 2.11 builds don't, perhaps they should)

not sure about the scala-swing one

**Comment by adriaanm** [comment]
Ah, thanks -- let's turn off fatal warnings everywhere.

**Comment by adriaanm** [comment]
As far as I understand, extraction run time should not be impacted in this way by the scala version. I mean, sbt doesn't use that version to compile the build, right? It's just for resolving dependencies that we need the scala version there (??)

**Comment by dwijnand** [comment]
That MiMa issue I solved already https://github.com/lightbend/mima/pull/308

**Comment by dwijnand** [comment]
I thought I saw that swoval failure, but I can't find anything.  Perhaps @eed3si9n is aware of it otherwise we can report it.

**Comment by eed3si9n** [comment]
The only file-not-found error that I've seen thus far are Coursier's https://github.com/coursier/coursier/issues/1185.
The scala-swing issue might be some transient issue while loading Swoval (native code that's used to list files). I've reported it as https://github.com/sbt/sbt/issues/4741

**Comment by SethTisue** [comment]
all three builds are now mostly on 1.3.0-RC2 (some individual projects remain on 1.2.8 for mostly uninvestigated reasons, uninvestigated by me anyway)
