### ISSUE TITLE
ScalaJS broken in the 2.11.x community build since build 502 / Mar 29, 2015

### ISSUE THREAD

**Issue by retronym** [scala/community-builds#95]
https://jenkins-dbuild.typesafe.com:8499/job/Community-2.11.x/502

```
[scala-js] [warn] 59 warnings found
[scala-js] [info] Main Scala API documentation successful.
[scala-js] [info] Packaging /mnt/dbuild/jenkinsdbuild2/localhome-a7/workspace/Community-2.11.x/target-0.9.1/project-builds/scala-js-3700267f500d7b7c607d6b595749c52787a06149/library/target/scala-2.11/scalajs-library-0.6.3-dbuildx3700267f500d7b7c607d6b595749c52787a06149-javadoc.jar ...
[scala-js] [info] Done packaging.
[scala-js] [warn] No main class detected
[scala-js] [info] Compiling 98 Scala sources to /mnt/dbuild/jenkinsdbuild2/localhome-a7/workspace/Community-2.11.x/target-0.9.1/project-builds/scala-js-3700267f500d7b7c607d6b595749c52787a06149/javalib/target/scala-2.11/classes...
[scala-js] [info] Compiling 4 Scala sources to /mnt/dbuild/jenkinsdbuild2/localhome-a7/workspace/Community-2.11.x/target-0.9.1/project-builds/scala-js-3700267f500d7b7c607d6b595749c52787a06149/library-aux/target/scala-2.11/classes...
[scala-js] [info] Compiling 35 Scala sources to /mnt/dbuild/jenkinsdbuild2/localhome-a7/workspace/Community-2.11.x/target-0.9.1/project-builds/scala-js-3700267f500d7b7c607d6b595749c52787a06149/javalanglib/target/scala-2.11/classes...
[scala-js] [info] Compiling 542 Scala sources to /mnt/dbuild/jenkinsdbuild2/localhome-a7/workspace/Community-2.11.x/target-0.9.1/project-builds/scala-js-3700267f500d7b7c607d6b595749c52787a06149/scalalib/target/scala-2.11/classes...
[scala-js] [error] error: Error: scalajs takes no options
[scala-js] [error] one error found
[scala-js] java.lang.RuntimeException: Nonzero exit code returned from runner: 1
[scala-js] 	at scala.sys.package$.error(package.scala:27)
[scala-js] 	at ExternalCompile$$anonfun$4$$anonfun$7$$anonfun$ExternalCompile$$anonfun$$anonfun$$doCompile$1$1.apply(ExternalCompile.scala:80)
[scala-js] 	at ExternalCompile$$anonfun$4$$anonfun$7$$anonfun$ExternalCompile$$anonfun$$anonfun$$doCompile$1$1.apply(ExternalCompile.scala:80)
[scala-js] 	at scala.Option.foreach(Option.scala:236)
[scala-js] 	at ExternalCompile$$anonfun$4$$anonfun$7.ExternalCompile$$anonfun$$anonfun$$doCompile$1(ExternalCompile.scala:80)
[scala-js] 	at ExternalCompile$$anonfun$4$$anonfun$7.apply(ExternalCompile.scala:93)
[scala-js] 	at ExternalCompile$$anonfun$4$$anonfun$7.apply(ExternalCompile.scala:45)
[scala-js] 	at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:186)
[scala-js] 	at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:186)
[scala-js] 	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:200)
[scala-js] 	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:196)
[scala-js] 	at sbt.Difference.apply(Tracked.scala:175)
[scala-js] 	at sbt.Difference.apply(Tracked.scala:157)
[scala-js] 	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:196)
[scala-js] 	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:195)
[scala-js] 	at sbt.Difference.apply(Tracked.scala:175)
[scala-js] 	at sbt.Difference.apply(Tracked.scala:151)
[scala-js] 	at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:195)
[scala-js] 	at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:193)
[scala-js] 	at ExternalCompile$$anonfun$4.apply(ExternalCompile.scala:100)
[scala-js] 	at ExternalCompile$$anonfun$4.apply(ExternalCompile.scala:19)
[scala-js] 	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[scala-js] 	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
[scala-js] 	at sbt.std.Transform$$anon$4.work(System.scala:63)
[scala-js] 	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
[scala-js] 	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
[scala-js] 	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[scala-js] 	at sbt.Execute.work(Execute.scala:235)
[scala-js] 	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
[scala-js] 	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
[scala-js] 	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
[scala-js] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[scala-js] 	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
[scala-js] 	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
[scala-js] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
[scala-js] 	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
[scala-js] 	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
[scala-js] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
[scala-js] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
[scala-js] 	at java.lang.Thread.run(Thread.java:701)
[scala-js] [error] (scalalib/compile:compile) Nonzero exit code returned from runner: 1
```

/cc @sjrd

**Comment by retronym** [comment]
That error message comes from scala:

```
% git grep "takes no options"
src/compiler/scala/tools/nsc/plugins/Plugin.scala:    if (!options.isEmpty) error(s"Error: $name takes no options")
test/files/neg/t7494-no-options.check:error: Error: ploogin takes no options
```

**Comment by retronym** [comment]
Looks like the regression comes form here: https://github.com/scala/scala/pull/4318/files

**Comment by retronym** [comment]
https://jenkins-dbuild.typesafe.com:8499/job/Community-2.11.x/513/console
